#docker compose配置文件
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bingzhi-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Lzb20060908
      MYSQL_DATABASE: bingzhi_vinyl
    ports:
      - "3306:3306"  #端口映射：主机3306-》容器3306
    volumes:
      - mysql-data:/var/lib/mysql  #数据持久化

  redis:
    image: redis:7-alpine
    container_name: bingzhi-redis
    ports:
      - "6379:6379"

  app:
    build: .  #使用当前目录的dockerfile构建镜像
    container_name: bingzhi-app
    depends_on:  #依赖关系（先启动mysql和redis）
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bingzhi_vinyl?useSSL=false&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Lzb20060908
      SPRING_REDIS_HOST: redis

volumes:
  mysql-data:
