#启动时能看到店名，更专业
spring:
  application:
    name: IcePaper Vinyl Store

  datasource:
    url: jdbc:mysql://localhost:3306/bingzhi_vinyl?serverTimezone=Asia/Shanghai&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: Lzb20060908
    driver-class-name: com.mysql.cj.jdbc.Driver  #mysql8.0的官方驱动类

mybatis:
  mapper-locations: classpath:mapper/*.xml  #告诉mybatis我的sql语句所在的文件
  type-aliases-package: com.bingzhi.vinyl.entity #写sql时，不用写完整的类名
  configuration:
    map-underscore-to-camel-case: true  #下划线拼接自动转为驼峰


server:
  port: 8080

